#ifndef SIGNAL_H
#define SIGNAL_H

enum Signal
{
	ERROR_DISPLAY,
	ERROR_COMMAND, ERROR_OPTION,
	ERROR_LENGTH_EXCEED, ERROR_LENGTH_ZERO,
	SUCCESS_ADD, SUCCESS_UPDATE, SUCCESS_DELETE
};

#endif